# LaTeXmk configuration for amznotes
# Use LuaLaTeX for compilation (required by the emoji package)
$pdf_mode = 4;

# LuaLaTeX options
$lualatex = 'lualatex -synctex=1 -interaction=nonstopmode %O %S';

# BibTeX options (if needed)
$bibtex_use = 2;

# Clean up additional files generated by amznotes
$clean_ext = "bbl synctex.gz run.xml";

# Preview options
$preview_mode = 1;  # 0=off, 1=on for continuous preview
